create table person
(
    id         bigint generated by default as identity,
    name       varchar(255),
    age        integer,
    birth_date date,
    created_at timestamp(6),
    primary key (id)
);
